apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-patient
  template:
    metadata:
      labels:
        app: ms-patient
    spec:
      containers:
      - name: ms-patient-container
        image: ms-patient-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ms-patient
spec:
  selector:
    app: ms-patient
  ports:
    - port: 8081
      targetPort: 8081
